name: Book Golf Tee Time

on:
  schedule:
    # Runs at 6:50 AM Pacific Time (13:50 UTC) on Saturdays and Sundays only
    - cron: '50 13 * * 0,6,4'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  golf-booking:
    # Only run if WORKFLOW_ENABLED is true or this is a manual trigger
    if: github.event_name == 'workflow_dispatch' || vars.WORKFLOW_ENABLED == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          make install
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      
      - name: Create .env file with secrets
        run: |
          cat > .env << 'EOF'
          GOLF_USERNAME=${{ secrets.GOLF_USERNAME }}
          GOLF_PASSWORD=${{ secrets.GOLF_PASSWORD }}
          BOOKING_URL=${{ vars.BOOKING_URL }}
          PREFERRED_TIME_RANGE=${{ vars.PREFERRED_TIME_RANGE }}
          NUMBER_OF_PLAYERS=${{ vars.NUMBER_OF_PLAYERS }}
          TEST_MODE=${{ vars.TEST_MODE }}
          EOF 

      - name: Run login script
        run: make run

      - name: Upload logs and screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            chronogolf_output/run_*/logs/
            chronogolf_output/run_*/screenshots/