name: Morning Chronogolf Login

on:
  schedule:
    # Runs at 6:55 AM UTC every day
    - cron: '55 6 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  golf-booking:
    # Only run if WORKFLOW_ENABLED is true or this is a manual trigger
    if: github.event_name == 'workflow_dispatch' || secrets.WORKFLOW_ENABLED == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      
      - name: Create .env file with secrets
        run: |
          echo "GOLF_USERNAME=${{ secrets.GOLF_USERNAME }}" > .env
          echo "GOLF_PASSWORD=${{ secrets.GOLF_PASSWORD }}" >> .env
          echo "BOOKING_URL=${{ secrets.BOOKING_URL }}" >> .env
          echo "PREFERRED_TIME_RANGE=${{ secrets.PREFERRED_TIME_RANGE }}" >> .env
          echo "NUMBER_OF_PLAYERS=${{ secrets.NUMBER_OF_PLAYERS }}" >> .env
      
      - name: Run login script
        run: make run